version: '3'

services:

  ariadne-client:
    build:
      context: .
      dockerfile: client/docker/client-staging.dockerfile
      args:
        APP_THEME: ${APP_THEME}
    restart: always
    container_name: data-catalogue
    environment:
      VIRTUAL_HOST: ads24staging0
      VIRTUAL_PATH: /data-catalogue/


  ariadne-server:
    build:
      context: .
      dockerfile: server/docker/server.dockerfile
      args:
        APP_THEME: ${APP_THEME}
    working_dir: /var/www/html
    restart: always
    container_name: data-catalogue-api
    environment:
      VIRTUAL_HOST: ads24staging0
      VIRTUAL_PATH: /data-catalogue-api/
      VIRTUAL_DEST: /

networks:
  default:
    name: nginx-proxy
    external: true
